### ISSUE TITLE
deploy failed on okd 3.11

### ISSUE THREAD

**Issue by vanloswang** [raffaelespazzoli/credscontroller#8]
The vault container failed to run with following error logs:
```
chown: /vault/file: Operation not permitted
chown: /vault/file: Operation not permitted
```

I have found that the log infomation is located ./vendor/github.com/hashicorp/vault/vault/init.go.
I also try to execute the chown command and it return following information to me.
```
/ # chown vault:vault /vault/file
chown: /vault/file: Operation not permitted
```
The persist volume is provided by NFS server within the cluster. The ownner for the NFS export path is nobody:nobody.
I also try to change the default scc to allow pod run as any, but it is not work.
I also try to rebuild the vault container and remove the command that will chown the file /vault/file, then the pod will up, but I can not visit the web. It seems like it is not the right way to resolve this issue.
Could you give me some suggestion to fix this issue?

**Comment by raffaelespazzoli** [comment]
hi @vanloswang , I am not maintaining this repo anymore. While the approach explained in this repo is probably still valid, I now recommend the approach explained here:
https://blog.openshift.com/vault-integration-using-kubernetes-authentication-method/
https://blog.openshift.com/integrating-vault-with-legacy-applications/

In partuclar the last blog post points to this repo: https://github.com/openlab-red/hashicorp-vault-for-openshift , which has more up to date and tested instructions to setup Vault.

Back to you error it looks like for some reason you don't have the right permissions on the mounted volume. Try to fix it using the supplemental group option on your pod and adding the group id that you have defined on that NFS mount.

**Comment by vanloswang** [comment]
OK，Thank you very much.
